version: '3.8'
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '33:3306'
    networks:
      default:

    
  api:
    container_name: API
    image: portfolioapi:13
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - ./.env
    networks:
      default:


networks:
  default:
    driver: bridge


