version: '3.8'
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '33:3306'
    networks:
      default:
        ipv4_address: 192.168.213.0

    
  api:
    container_name: API
    image: portfolioapi:13
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - ./.env
    networks:
      default:
        ipv4_address: 192.168.123.0


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.123.0/24

