version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
  
  express:
    depends_on:
      - mysqldb
    build: 
      dockerfile: dockerfile
    env_file:
      - ./.env
    links:
      - "mysqldb:database"


    