version: '3.8'
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 33:3306
  
  express:
    depends_on:
      - mysqldb 
    image: portfolioapi:06
    env_file:
      - ./.env



    