version: '3.8'
services:
  mysqlDB:
    image: mysql:latest
    env_file:
      - ./.env
    enviroment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $DB_PORT:3306
  
  express:
    depends_on:
      - mysqlDB
    image: portfolioapi
    env_file:
      - ./.env


    